---
name: Windows GitHub CI for 1.1.1

on: [pull_request, push, workflow_dispatch]


jobs:
  shared:
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2022
        platform:
        - arch: win64
          config: VC-WIN64A
        - arch: win32
          config: VC-WIN32 --strict-warnings
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform.arch }}
    - uses: ilammy/setup-nasm@v1
      with:
        platform: ${{ matrix.platform.arch }}
    - uses: shogo82148/actions-setup-perl@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure no-makedepend ${{ matrix.platform.config }}
        perl configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake /S
    - name: install
      # Run on 64 bit only as 32 bit is slow enough already
      if: $${{ matrix.platform.arch == 'win64' }}
      run: |
        mkdir _dest
        nmake install DESTDIR=_dest
      working-directory: _build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}-${{ matrix.platform.arch }}
        path: _build/
  plain:
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2022
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: shogo82148/actions-setup-perl@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure no-makedepend no-shared VC-WIN64A-masm
        perl configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake /S
  minimal:
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2022
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: shogo82148/actions-setup-perl@v1
    - name: prepare the build directory
      run: mkdir _build
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure no-makedepend no-deprecated no-asm -DOPENSSL_SMALL_FOOTPRINT VC-WIN64A
        perl configdata.pm --dump
    - name: build
      working-directory: _build
      run: nmake # verbose, so no /S here


